CREATE TABLE AUTOR (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CODIGO CHAR(4),
    NOMBRE VARCHAR(40) NOT NULL,
    APELLIDOS VARCHAR(60) NOT NULL,
    CONSTRAINT ID_AUTOR_PK PRIMARY KEY (ID)
);

CREATE TABLE LIBROS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    NOMBRE VARCHAR(40) NOT NULL,
    AUTOR INTEGER,
    PRECIO DECIMAL(7,2),
    FOTO VARCHAR(30),
    FECHA_EDICION DATE,
    ISBN CHAR(13),
    FAVORITOS BOOLEAN,
    GENERO VARCHAR(30) NOT NULL,
    CONSTRAINT ID_LIBROS_PK PRIMARY KEY (ID),
    CONSTRAINT PROV_AUTOR_FK FOREIGN KEY (AUTOR) REFERENCES AUTOR (ID)
);
